# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Billy"

#  Session Engine
#  simple session engine

session: Simple

# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
    template_toolkit:
        encoding:  'utf8'
        start_tag: '[%'
        end_tag:   '%]'

# DB connection settings
plugins:
    Database:
        driver: "SQLite"
#       database: "/home/cgonzalez/project/Billy/sql/billy_invoice_test.sqlite"
#       Windows Path to sqlite file:
        database: "C:\Users\cgonzalez\Documents\GitHub\Billy\sql\billy_invoice_test.sqlite"


	
