# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Billy"

# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
    template_toolkit:
        encoding:  'utf8'
        start_tag: '[%'
        end_tag:   '%]'

# DB connection settings
plugins:
    Database:
        driver: "SQLite"
        database: "/home/cgonzalez/project/Billy/sql/billy_invoice_test.sqlite"


#  I think its a better idea to store company info in app config then store it per invoice
# Company Information Setting
Company_information:
	company_name: "Test1"
	address: "123 Devoe St"
	city: "New York"
	state: "New York"
	zipcode: "100019"
	country: "USA"

# Company Shipment Setting:
Company_shipment_setting:
	company_name: "Test1"
	address: "PO BOX Address"
	city: "New York"
	state: "New York"
	zipcode: "10015"
	country: "USA"	
	
